            <div class="row customers">
                <div class="col-md-12">
                    <span class="title">Co o nás tvrdí zákazníci</span>
                    <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate nec neque quis posuere. Aliquam a nulla vel felis venenatis interdum. Narhoncus lobortis tortor, tempor egestas mi vestibulum a. Nunc vitae augue ac lorem fermentum consectetur. Vestibulum egestas.</p>
                    <img src="images/customers/sign1.png" alt=""><br />
                    <span class="name">Enya Volšanská</span><br />
                    <span class="sub">Hlídací maniak v Můj Domov, s.r.o.</span>
                </div>
            </div>