user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

homepage_index:
    path:    /
    defaults:  { _controller: AppBundle:Homepage:index }

# Webhosting
webhosting:
    path:      /webhosting/
    defaults:  { _controller: AppBundle:Webhosting:index }

webhosting_sale:
    path:      /webhosting/{sale}/
    defaults:  { _controller: AppBundle:Webhosting:sale}

# Contact
contact:
    path:      /contact/
    defaults:  { _controller: AppBundle:Contact:index }