subreg:
    resource: "@SubregBundle/Resources/config/routing.yml"
    prefix:   /

homepage_index:
    path:    /
    defaults:  { _controller: AppBundle:Homepage:index }

# Webhosting
webhosting:
    path:      /webhosting/
    defaults:  { _controller: AppBundle:Webhosting:index }

webhosting_sale:
    path:      /webhosting/{sale}/
    defaults:  { _controller: AppBundle:Webhosting:sale}