security:
    encoders:
        Application\UserBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: UserBundle:User, property: username }

        in_memory:
            memory: ~

    firewalls:
        admin_area:
            pattern: ^/admin
            http_basic: ~
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
    
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }