<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Frostbit.cz</title>
<base href="/">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
    ->prependStylesheet($this->basePath() . '/css/homepage.css')
    ->prependStylesheet($this->basePath() . '/css/bootstrap.css') ?>
<?php echo $this->headScript()
    ->prependFile($this->basePath() . '/js/bootstrap.min.js')
    ->prependFile($this->basePath() . '/js/jquery.min.js')
    ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath() . '/js/html5shiv.js', 'text/javascript', array('conditional' => 'lt IE 9',))
; ?>
</head>
    <body>
        <header>
            <div class="container">
                <a href="/"><div class="col-md-4 logotype"></div></a>
                <div class="col-md-8 navigation">
                    <ul class="navigation">
                        <li><a href="/cenik-domen/">Domény</a></li>
                        <li>Webhosting</li>
                        <li>Kontakt</li>
                    </ul>
                </div>
            </div>  
        </header>

        <div class="container">
            <div class="carousel-box">
                <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                    <!-- Indicators -->
                    <ol class="carousel-indicators">
                        <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    </ol>

                    <!-- Wrapper for slides -->
                     <div class="carousel-inner">
                        <div class="item active">
                            <img src="images/carousel/fotbal.png" alt="">
                            <div class="carousel-caption">
                                <span class="title">Hrajte na internetu Evropskou ligu</span>
                                <span class="content">.EU jen za 49,- Kč, ideálně v kombinaci se službou<br />Moje stránky nebo e-shopem</span>
                                <a href="#" class="btn-more" style="right: 120px;">více informací</a>
                            </div>
                        </div>
                        <div class="item">
                            <img src="images/carousel/cms.png" alt="...">
                            <div class="carousel-caption">
                                <span class="title"><strong>Multihosting</strong> poskládejte si to vedle sebe </span>
                                <span class="content">Až 10 webů v jednom balíčku za jednu cenu</span>
                                <a href="#" class="btn-more" style="right: 13px;">více informací</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <?php echo $this->content; ?>

           <div class="row footer">
                <div class="col-md-3">
                    <span class="title">produkty</span>
                    <ul>
                        <li><a href="/">Domény</a></li>
                        <li><a href="/">Webhosting</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">frostbit.cz</span>
                    <ul>
                        <li><a href="/">Novinky</a></li>
                        <li><a href="/blog">Blog</a></li>
                        <li><a href="/">Nápověda</a></li>
                        <li><a href="/">Kontakt</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">sledujte nás</span>
                    <ul>
                        <li><a href="" target="_blank">Facebook</a></li>
                        <li><a href="" target="_blank">Twitter</a></li>
                        <li><a href="" target="_blank">Google+</a></li>
                        <li><a href="" target="_blank">Instagram</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">kontaktujte nás</span>
                    <ul>
                        <li><a href="mailto:info@frostbit.cz">info@frostbit.cz</a></li>
                    </ul>
                </div>
            </div>

            <div class="row bottom">
                <div class="col-md-6 logo_icon">© 2014 Frostbit.cz</div>
                <div class="col-md-6 link">www.frostbit.cz</div>
            </div>

        </div>
    </body>
</html>