<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Frostbit.cz</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/main.css?v108" media="screen" rel="stylesheet" type="text/css">
<!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script type="text/javascript" src="/js/respond.min.js"></script><![endif]-->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="//code.jquery.com/ui/1.11.2/jquery-ui.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body class="<?php if(!$this->isHomepage) { echo "tiny-header"; } ?>">
    <div class="container">
        <div class="row">
            <div class="col-md-5 logo">
                <a href="#"><img src="/images/logo.png" alt="Frostbit.cz"></a>
                <div class="toggle">
                    <a href="#"><i class="fa fa-bars fa-lg"></i></a>
                </div>
            </div>
            <div class="col-md-7 navigation">
                <ul>
                    <li><a href="#">Domény</a></li>
                    <li><a href="/webhosting">Webhosting</a></li>
                    <li><a href="#">Kontakt</a></li>
                </ul>
            </div>
        </div>

        <!-- Mobile / tablets navigation -->
        <div class="responsive-navigation" style="display: none;">
            <ul>
                <li>Domény</li>
                <li>Webhosting</li>
                <li>Kontakt</li>
            </ul>
        </div>

        <?php echo $this->content; ?>

        <div class="row footer">
                <div class="col-md-3">
                    <span class="title">produkty</span>
                    <ul>
                        <li><a href="/">Domény</a></li>
                        <li><a href="/">Webhosting</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">frostbit.cz</span>
                    <ul>
                        <li><a href="/">Novinky</a></li>
                        <li><a href="/blog">Blog</a></li>
                        <li><a href="/">Nápověda</a></li>
                        <li><a href="/">Kontakt</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">sledujte nás</span>
                    <ul>
                        <li><a href="" target="_blank">Facebook</a></li>
                        <li><a href="" target="_blank">Twitter</a></li>
                        <li><a href="" target="_blank">Google+</a></li>
                        <li><a href="" target="_blank">Instagram</a></li>
                    </ul>
                </div>
                <div class="col-md-3">
                    <span class="title">kontaktujte nás</span>
                    <ul>
                        <li><a href="mailto:info@frostbit.cz">info@frostbit.cz</a></li>
                    </ul>
                </div>
            </div>

            <div class="row bottom">
                <div class="col-md-6 logo_icon">© 2014 Frostbit.cz</div>
            </div>

        </div>

    </div>

    <script type="text/javascript" src="/js/main.min.js?v10"></script>
</body>
</html>