<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Frostbit.cz</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
<link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/main.css?version=105" media="screen" rel="stylesheet" type="text/css">
<!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script type="text/javascript" src="/js/respond.min.js"></script><![endif]-->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-md-5 logo">
                <a href="#"><img src="/images/logo.png" alt="Frostbit.cz"></a>
                <div class="toggle">
                    <a href="#"><i class="fa fa-bars fa-lg"></i></a>
                </div>
            </div>
            <div class="col-md-7 navigation">
                <ul>
                    <li><a href="#">Domény</a></li>
                    <li><a href="#">Webhosting</a></li>
                    <li><a href="#">Kontakt</a></li>
                </ul>
            </div>
        </div>

        <!-- Mobile / tablets navigation -->
        <div class="responsive-navigation" style="display: none;">
            <ul>
                <li>Domény</li>
                <li>Webhosting</li>
                <li>Kontakt</li>
            </ul>
        </div>

        <!-- Carousel -->
        <div class="row">
            <div class="col-md-12">
                <div id="carousel" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="images/carousel/microsoft.png" class="top-image" alt="Microsoft"><br />
                            <span class="title">Celebrate our Gold Partnership.</span>
                            <p class="description">Enjoy the highest accreditation of Microsoft certified support, <br />from Windows Servers to our award-winning Microsoft Private Cloud.</p>
                        </div>
                        <div class="item">
                            <img src="images/carousel/microsoft.png" class="top-image" alt="Microsoft"><br />
                            <span class="title">Celebrate our Silver Partnership.</span>
                            <p class="description">Enjoy the highest accreditation of Microsoft certified support, <br />from Windows Servers to our award-winning Microsoft Private Cloud.</p>
                        </div>
                    </div>
                    <ol class="carousel-indicators">
                        <li data-target="#carousel" data-slide-to="0" class="active"></li>
                        <li data-target="#carousel" data-slide-to="1"></li>
                    </ol>
                </div>
            </div>
        </div>

        <!-- Products -->
        <div class="row">
            <div class="col-md-6">
                <div class="product">
                    <h2>Domény</h2>
                    <img src="images/products/domain_icon.png" alt="Domény">
                    <ul>
                        <li><strong>Přesměrování zdarma</strong> bez potřeby hostingu</li>
                        <li>Snadná správa <strong>DNS záznamů</strong></li>
                        <li><strong>Zabezpečení domén</strong> pomocí DNSSEC</li>
                        <li>Registrace domény <strong>během okamžiku</strong></li>
                    </ul>
                    <span class="price-txt">již od <span class="price">199 CZK</span></span>
                    <a href="#" class="btn btn-success">Objednat</a>
                </div>
            </div>
            <div class="col-md-6">
                <div class="product">
                    <h2>Webhosting</h2>
                    <img src="images/products/webhosting_icon.png" alt="Webhosting">
                    <ul>
                        <li><strong>Přesměrování zdarma</strong> bez potřeby hostingu</li>
                        <li>Snadná správa <strong>DNS záznamů</strong></li>
                        <li><strong>Zabezpečení domén</strong> pomocí DNSSEC</li>
                        <li>Registrace domény <strong>během okamžiku</strong></li>
                    </ul>
                    <span class="price-txt">již od <span class="price">20 CZK</span></span>
                    <a href="#" class="btn btn-success">Objednat</a>
                </div>
            </div>
        </div>

    </div>

    <script type="text/javascript" src="/js/main.min.js"></script>
</body>
</html>