            <div class="row products">
                <div class="col-md-6">
                    <div class="product">
                        <img src="images/products/domain_icon.png" alt="Domains">
                        <h2>Domény</h2>
                        <ul>
                            <li><strong>Přesměrování zdarma</strong> bez potřeby hostingu</li>
                            <li>Snadná správa <strong>DNS záznamů</strong></li>
                            <li><strong>Zabezpečení domén</strong> pomocí DNSSEC</li>
                            <li>Registrace domény <strong>během okamžiku</strong></li>
                        </ul>

                        <span class="price_txt">již od</span> <span class="price">199,-</span>
                        <span class="more_info">
                            <a href="" class="btn btn-success">více informací</a>
                        </span>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="product">
                        <img src="images/products/webhosting_icon.png" alt="Domains">
                        <h2>Webhosting</h2>
                        <ul>
                            <li><strong>Neomezený počet</strong> zaparkovaných domén</li>
                            <li>Podpora PHP 5.3, 5.4 & 5.5</li>
                            <li><strong>Emailové schránky zdarma</strong> v rámci hostingu</li>
                            <li>Neomezený počet <strong>MySQL databází s podporou innoDB</strong></li>
                        </ul>

                        <span class="price_txt">již od</span> <span class="price">29,-</span>
                        <span class="more_info">
                            <a href="" class="btn btn-success">více informací</a>
                        </span>
                    </div>
                </div>
            </div>

            <div class="row customers">
                <div class="col-md-12">
                    <span class="title">Co o nás tvrdí zákazníci</span>
                    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                         <div class="carousel-inner">
                            <div class="item active">
                                <p class="description">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut vulputate nec neque quis posuere. Aliquam a nulla vel felis venenatis interdum. Narhoncus lobortis tortor, tempor egestas mi vestibulum a. Nunc vitae augue ac lorem fermentum consectetur. Vestibulum egestas.</p>
                                <img src="images/customers/sign1.png" alt=""><br />
                                <span class="name">Enya Volšanská</span><br />
                                <span class="sub">Hlídací maniak v Můj Domov, s.r.o.</span>  
                            </div>
                            <div class="item">
                                <p class="description">Maecenas consectetur libero nunc, sed consequat sem molestie sed. Sed accumsan eros sit amet interdum facilisis. Cras a molestie sapien. Donec sit amet semper metus. Curabitur sit amet neque nec ligula mattis feugiat in ac lectus. Nunc lobortis mollis diam id tincidunt. </p>
                                <img src="images/customers/sign1.png" alt=""><br />
                                <span class="name">Darth Vader</span><br />
                                <span class="sub">CEO at death Star, Inc.</span>  
                            </div>
                        </div>
                    </div>
                </div>
            </div>